project:
  title: "HTML Template"
  # output-dir: _output
  render:
    - "main.qmd"

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    code-tools: true
    code-fold: false
    code-link: true
    code-block-bg: "#f1f3f5"
    theme: [simplex, style.scss]
    mainfont: 'Source Sans Pro'
    monofont: 'Source Code Pro'
    fontsize: 16px
    fig-format: retina
    fig-width: 8
    fig-height: 6
    fig-align: center
    lightbox: true
    tbl-cap-location: bottom
    fig-cap-location: bottom
    reference-location: margin
    citation-location: margin
    standalone: true
    embed-resources: true

author: "Maximilian Rohde"

date: today
date-format: long

knitr:
  opts_chunk: 
    dev: "ragg_png"

execute:
  warning: false
  message: false

